services:
#    lsi_market.example:
#        class: LSI\MarketBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    lsi_market.email.civilink_mailer:
        class: LSI\MarketBundle\Email\EnvoyerMail
        arguments:
            - "@mailer"
            - "%mailer_user%"

#    lsi_market.file.twig.extension:
#        class: LSI\MarketBundle\Extensions\ExistenceFichier
#        tags:
#            -{ name: twig.extension }

#    services:
#        lsi_market.service.listener:
#            class: LSI\MarketBundle\Listener\LoadDataListener
#    	    tags:
#       		        - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }

    lsi_market.service.listener:
        class: LSI\MarketBundle\Listener\LoadDataListener
        tags:
            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }

# service pour supprimer un fichier

    lsi_market.file_remove:
        class: LSIMarketBundle\Services\FileRemove
        arguments: ['%stamp_dir%']

# service pour telecharger un fichier

    lsi_market.file_upload:
        class: LSIMarketBundle\Services\FileUpload
        arguments: ['%stamp_dir%']