<?php

namespace Proxies\__CG__\LSI\MarketBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Annonce extends \LSI\MarketBundle\Entity\Annonce implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'id', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'titre', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'description', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'regleCond', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'prixDefaut', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'dateCreation', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'typeforfait', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'heureCreation', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'annonceUpdateAt', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'annonceEtat', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'typeAnnul', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'assurances', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'mairie', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'images', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'caracteristiques', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'categorie', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'nature', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'fonction', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'calendrier', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'adresse', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'pulicMairie', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'pulicAdministre', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'tarifAdminisEpci', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'tarifNonAdminisEpci', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'tarifNonAdminis', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'tarifEpci', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'tarifNonEpci'];
        }

        return ['__isInitialized__', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'id', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'titre', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'description', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'regleCond', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'prixDefaut', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'dateCreation', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'typeforfait', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'heureCreation', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'annonceUpdateAt', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'annonceEtat', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'typeAnnul', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'assurances', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'mairie', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'images', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'caracteristiques', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'categorie', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'nature', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'fonction', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'calendrier', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'adresse', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'pulicMairie', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'pulicAdministre', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'tarifAdminisEpci', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'tarifNonAdminisEpci', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'tarifNonAdminis', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'tarifEpci', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Annonce' . "\0" . 'tarifNonEpci'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Annonce $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegleCond($regleCond)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegleCond', [$regleCond]);

        return parent::setRegleCond($regleCond);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegleCond()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegleCond', []);

        return parent::getRegleCond();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixDefaut($prixDefaut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixDefaut', [$prixDefaut]);

        return parent::setPrixDefaut($prixDefaut);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixDefaut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixDefaut', []);

        return parent::getPrixDefaut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureCreation($heureCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureCreation', [$heureCreation]);

        return parent::setHeureCreation($heureCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureCreation', []);

        return parent::getHeureCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnonceUpdateAt($annonceUpdateAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnonceUpdateAt', [$annonceUpdateAt]);

        return parent::setAnnonceUpdateAt($annonceUpdateAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnonceUpdateAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnonceUpdateAt', []);

        return parent::getAnnonceUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnonceEtat($annonceEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnonceEtat', [$annonceEtat]);

        return parent::setAnnonceEtat($annonceEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnonceEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnonceEtat', []);

        return parent::getAnnonceEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeAnnul($typeAnnul)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeAnnul', [$typeAnnul]);

        return parent::setTypeAnnul($typeAnnul);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeAnnul()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeAnnul', []);

        return parent::getTypeAnnul();
    }

    /**
     * {@inheritDoc}
     */
    public function setMairie(\LSI\MarketBundle\Entity\Mairie $mairie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMairie', [$mairie]);

        return parent::setMairie($mairie);
    }

    /**
     * {@inheritDoc}
     */
    public function getMairie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMairie', []);

        return parent::getMairie();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\LSI\MarketBundle\Entity\Image $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', [$image]);

        return parent::addImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\LSI\MarketBundle\Entity\Image $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', [$image]);

        return parent::removeImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function setImages($images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImages', [$images]);

        return parent::setImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function addCaracteristique(\LSI\MarketBundle\Entity\Caracteristique $caracteristique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCaracteristique', [$caracteristique]);

        return parent::addCaracteristique($caracteristique);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCaracteristique(\LSI\MarketBundle\Entity\Caracteristique $caracteristique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCaracteristique', [$caracteristique]);

        return parent::removeCaracteristique($caracteristique);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaracteristiques()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaracteristiques', []);

        return parent::getCaracteristiques();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(\LSI\MarketBundle\Entity\Categorie $categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function addCalendrier(\LSI\MarketBundle\Entity\Calendrier $calendrier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCalendrier', [$calendrier]);

        return parent::addCalendrier($calendrier);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCalendrier(\LSI\MarketBundle\Entity\Calendrier $calendrier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCalendrier', [$calendrier]);

        return parent::removeCalendrier($calendrier);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalendrier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalendrier', []);

        return parent::getCalendrier();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(\LSI\MarketBundle\Entity\Adresse $adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setPulicMairie($pulicMairie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPulicMairie', [$pulicMairie]);

        return parent::setPulicMairie($pulicMairie);
    }

    /**
     * {@inheritDoc}
     */
    public function getPulicMairie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPulicMairie', []);

        return parent::getPulicMairie();
    }

    /**
     * {@inheritDoc}
     */
    public function setPulicAdministre($pulicAdministre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPulicAdministre', [$pulicAdministre]);

        return parent::setPulicAdministre($pulicAdministre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPulicAdministre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPulicAdministre', []);

        return parent::getPulicAdministre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarifAdminisEpci(\LSI\MarketBundle\Entity\TarifAdministreEpci $tarifAdminisEpci = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarifAdminisEpci', [$tarifAdminisEpci]);

        return parent::setTarifAdminisEpci($tarifAdminisEpci);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarifAdminisEpci()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarifAdminisEpci', []);

        return parent::getTarifAdminisEpci();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarifNonAdminisEpci(\LSI\MarketBundle\Entity\TarifAdministreNonEpci $tarifNonAdminisEpci = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarifNonAdminisEpci', [$tarifNonAdminisEpci]);

        return parent::setTarifNonAdminisEpci($tarifNonAdminisEpci);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarifNonAdminisEpci()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarifNonAdminisEpci', []);

        return parent::getTarifNonAdminisEpci();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarifNonAdmins(\LSI\MarketBundle\Entity\TarifNonAdministre $tarifNonAdmins = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarifNonAdmins', [$tarifNonAdmins]);

        return parent::setTarifNonAdmins($tarifNonAdmins);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarifNonAdmins()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarifNonAdmins', []);

        return parent::getTarifNonAdmins();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarifEpci(\LSI\MarketBundle\Entity\TarifEpci $tarifEpci = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarifEpci', [$tarifEpci]);

        return parent::setTarifEpci($tarifEpci);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarifEpci()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarifEpci', []);

        return parent::getTarifEpci();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarifNonEpci(\LSI\MarketBundle\Entity\TarifEpci $tarifNonEpci = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarifNonEpci', [$tarifNonEpci]);

        return parent::setTarifNonEpci($tarifNonEpci);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarifNonEpci()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarifNonEpci', []);

        return parent::getTarifNonEpci();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarifNonAdminis(\LSI\MarketBundle\Entity\TarifNonAdministre $tarifNonAdminis = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarifNonAdminis', [$tarifNonAdminis]);

        return parent::setTarifNonAdminis($tarifNonAdminis);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarifNonAdminis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarifNonAdminis', []);

        return parent::getTarifNonAdminis();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeforfait($typeforfait)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeforfait', [$typeforfait]);

        return parent::setTypeforfait($typeforfait);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeforfait()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeforfait', []);

        return parent::getTypeforfait();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssurances($assurances)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssurances', [$assurances]);

        return parent::setAssurances($assurances);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssurances()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssurances', []);

        return parent::getAssurances();
    }

    /**
     * {@inheritDoc}
     */
    public function setNature(\LSI\MarketBundle\Entity\Nature $nature = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNature', [$nature]);

        return parent::setNature($nature);
    }

    /**
     * {@inheritDoc}
     */
    public function getNature()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNature', []);

        return parent::getNature();
    }

    /**
     * {@inheritDoc}
     */
    public function setFonction(\LSI\MarketBundle\Entity\Fonction $fonction = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFonction', [$fonction]);

        return parent::setFonction($fonction);
    }

    /**
     * {@inheritDoc}
     */
    public function getFonction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFonction', []);

        return parent::getFonction();
    }

}
