<?php

namespace Proxies\__CG__\LSI\MarketBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mairie extends \LSI\MarketBundle\Entity\Mairie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'id', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'description', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'service', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'longitude', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'latitude', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'epci', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'budgetInitial', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'budgetRestant'];
        }

        return ['__isInitialized__', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'id', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'description', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'service', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'longitude', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'latitude', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'epci', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'budgetInitial', '' . "\0" . 'LSI\\MarketBundle\\Entity\\Mairie' . "\0" . 'budgetRestant'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mairie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setService($service)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setService', [$service]);

        return parent::setService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function getService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getService', []);

        return parent::getService();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setEpci(\LSI\MarketBundle\Entity\Epci $epci = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEpci', [$epci]);

        return parent::setEpci($epci);
    }

    /**
     * {@inheritDoc}
     */
    public function getEpci()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpci', []);

        return parent::getEpci();
    }

    /**
     * {@inheritDoc}
     */
    public function setBudgetInitial($budgetInitial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBudgetInitial', [$budgetInitial]);

        return parent::setBudgetInitial($budgetInitial);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudgetInitial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudgetInitial', []);

        return parent::getBudgetInitial();
    }

    /**
     * {@inheritDoc}
     */
    public function setBudgetRestant($budgetRestant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBudgetRestant', [$budgetRestant]);

        return parent::setBudgetRestant($budgetRestant);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudgetRestant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudgetRestant', []);

        return parent::getBudgetRestant();
    }

}
