<?php

namespace LSI\MarketBundle\Repository;


use Doctrine\ORM\EntityRepository;
use LSI\MarketBundle\Entity\Annonce;
use LSI\MarketBundle\Entity\Statut;
/**
 * CalendrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendrierRepository extends \Doctrine\ORM\EntityRepository
{
	 public function findStatut($statut)
	{
        //$libelle = new Statut();
        $qb = $this->createQueryBuilder('c')
                   ->innerjoin('c.statut', 's')
                   ->addSelect('s')
                   ->where('s.id= :id')
                   ->setParameter('id', $statut);
        return $qb->getQuery()->getResult();

    }

    public function findPeriod ($date)
    {
        //$date = date ( "Y-m-d" );
        $sql = $this->createQueryBuilder ( 'c' )
            ->select ( 'c' )
            ->Where ( "c.fin >= :debut" )
            ->andWhere ( "c.debut <= :fin" )
            ->setParameter ( 'debut' , $date )
            ->orderBy ( 'c.debut' , 'ASC' );
        return $sql->getQuery ()->getResult ();
    }

   /* public function PeriodDispo($annonce)
    { 
        $qb = $this->createQueryBuilder('c')
                   ->innerJoin('c.debut', 'd')
                   ->addSelect('d')
                   ->innerJoin('c.fin', 'f')
                   ->addSelect('f')
                   ->where('c.id = :id')
                   ->setParameter('id', $annonce);
    return  $qb->getQuery()->getResult();
      } */
}
