<?php

namespace LSI\MarketBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CodePostalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePostalRepository extends EntityRepository {
    public function findCodePostal($cp){
        $qb = $this->createQueryBuilder('cp')
            ->where('cp.code = :cp')
            ->setParameter('cp', $cp)
            ;
        return $qb->getQuery()->getScalarResult();
    }


}
