<?php

namespace LSI\MarketBundle\Repository;

/**
 * ConditionsGeneralesVentesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionsGeneralesVentesRepository extends \Doctrine\ORM\EntityRepository
{
}
