<?php

namespace LSI\MarketBundle\Repository;

/**
 * ConditionsGeneralesUtilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionsGeneralesUtilRepository extends \Doctrine\ORM\EntityRepository
{
}
