<?php

namespace LSI\MarketBundle\Repository;

/**
 * DemarcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemarcheRepository extends \Doctrine\ORM\EntityRepository
{
}
