<?php

namespace LSI\MarketBundle\Repository;

/**
 * PublicMairieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicMairieRepository extends \Doctrine\ORM\EntityRepository
{
}
