<?php

namespace LSI\MarketBundle\Repository;

/**
 * PublicAdministreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicAdministreRepository extends \Doctrine\ORM\EntityRepository
{
}
